/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.arap.tally;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class RecStatementVO extends SuperVO {
	private java.lang.String pk_recstatement;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_qryobj;
	private java.lang.String qryobj;
	private java.lang.String pk_currtype;
	private nc.vo.pub.lang.UFDouble bal_qua;
	private nc.vo.pub.lang.UFDouble bal_ori;
	private nc.vo.pub.lang.UFDouble bal_loc;
	private nc.vo.pub.lang.UFDouble gr_bal_loc;
	private nc.vo.pub.lang.UFDouble gl_bal_loc;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	
	//add for 新加坡BDA 20161111
	private nc.vo.pub.lang.UFDouble period1;
	private nc.vo.pub.lang.UFDouble period2;
	private nc.vo.pub.lang.UFDouble period3;
	private nc.vo.pub.lang.UFDouble period4;
	private nc.vo.pub.lang.UFDouble period5;
	private nc.vo.pub.lang.UFDouble period6;
	private nc.vo.pub.lang.UFDouble period7;
	private nc.vo.pub.lang.UFDouble period8;
	
	private nc.vo.pub.lang.UFBoolean iscancelaftercode;
	private String deadline;
	//add end

	public static final String PK_RECSTATEMENT = "pk_recstatement";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_QRYOBJ = "pk_qryobj";
	public static final String QRYOBJ = "qryobj";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String BAL_QUA = "bal_qua";
	public static final String BAL_ORI = "bal_ori";
	public static final String BAL_LOC = "bal_loc";
	public static final String GR_BAL_LOC = "gr_bal_loc";
	public static final String GL_BAL_LOC = "gl_bal_loc";
	
	public static final String PERIOD1 = "period1";
	public static final String PERIOD2 = "period2";
	public static final String PERIOD3 = "period3";
	public static final String PERIOD4 = "period4";
	public static final String PERIOD5 = "period5";
	public static final String PERIOD6 = "period6";
	public static final String PERIOD7 = "period7";
	public static final String PERIOD8 = "period8";
	public static final String ISCANCELAFTERCODE = "iscancelaftercode";
	public static final String DEADLINE = "deadline";
	
	/**
	 * 属性pk_recstatement的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_recstatement () {
		return pk_recstatement;
	}   
	/**
	 * 属性pk_recstatement的Setter方法.
	 * 创建日期:
	 * @param newPk_recstatement java.lang.String
	 */
	public void setPk_recstatement (java.lang.String newPk_recstatement ) {
	 	this.pk_recstatement = newPk_recstatement;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_qryobj的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_qryobj () {
		return pk_qryobj;
	}   
	/**
	 * 属性pk_qryobj的Setter方法.
	 * 创建日期:
	 * @param newPk_qryobj java.lang.String
	 */
	public void setPk_qryobj (java.lang.String newPk_qryobj ) {
	 	this.pk_qryobj = newPk_qryobj;
	} 	  
	/**
	 * 属性qryobj的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getQryobj () {
		return qryobj;
	}   
	/**
	 * 属性qryobj的Setter方法.
	 * 创建日期:
	 * @param newQryobj java.lang.String
	 */
	public void setQryobj (java.lang.String newQryobj ) {
	 	this.qryobj = newQryobj;
	} 	  
	/**
	 * 属性pk_currtype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_currtype () {
		return pk_currtype;
	}   
	/**
	 * 属性pk_currtype的Setter方法.
	 * 创建日期:
	 * @param newPk_currtype java.lang.String
	 */
	public void setPk_currtype (java.lang.String newPk_currtype ) {
	 	this.pk_currtype = newPk_currtype;
	} 	  
	/**
	 * 属性bal_qua的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_qua () {
		return bal_qua;
	}   
	/**
	 * 属性bal_qua的Setter方法.
	 * 创建日期:
	 * @param newBal_qua nc.vo.pub.lang.UFDouble
	 */
	public void setBal_qua (nc.vo.pub.lang.UFDouble newBal_qua ) {
	 	this.bal_qua = newBal_qua;
	} 	  
	/**
	 * 属性bal_ori的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_ori () {
		return bal_ori;
	}   
	/**
	 * 属性bal_ori的Setter方法.
	 * 创建日期:
	 * @param newBal_ori nc.vo.pub.lang.UFDouble
	 */
	public void setBal_ori (nc.vo.pub.lang.UFDouble newBal_ori ) {
	 	this.bal_ori = newBal_ori;
	} 	  
	/**
	 * 属性bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_loc () {
		return bal_loc;
	}   
	/**
	 * 属性bal_loc的Setter方法.
	 * 创建日期:
	 * @param newBal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setBal_loc (nc.vo.pub.lang.UFDouble newBal_loc ) {
	 	this.bal_loc = newBal_loc;
	} 	  
	/**
	 * 属性gr_bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGr_bal_loc () {
		return gr_bal_loc;
	}   
	/**
	 * 属性gr_bal_loc的Setter方法.
	 * 创建日期:
	 * @param newGr_bal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGr_bal_loc (nc.vo.pub.lang.UFDouble newGr_bal_loc ) {
	 	this.gr_bal_loc = newGr_bal_loc;
	} 	  
	/**
	 * 属性gl_bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGl_bal_loc () {
		return gl_bal_loc;
	}   
	/**
	 * 属性gl_bal_loc的Setter方法.
	 * 创建日期:
	 * @param newGl_bal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGl_bal_loc (nc.vo.pub.lang.UFDouble newGl_bal_loc ) {
	 	this.gl_bal_loc = newGl_bal_loc;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	public nc.vo.pub.lang.UFDouble getPeriod1() {
		return period1;
	}
	public void setPeriod1(nc.vo.pub.lang.UFDouble period1) {
		this.period1 = period1;
	}
	public nc.vo.pub.lang.UFDouble getPeriod2() {
		return period2;
	}
	public void setPeriod2(nc.vo.pub.lang.UFDouble period2) {
		this.period2 = period2;
	}
	public nc.vo.pub.lang.UFDouble getPeriod3() {
		return period3;
	}
	public void setPeriod3(nc.vo.pub.lang.UFDouble period3) {
		this.period3 = period3;
	}
	public nc.vo.pub.lang.UFDouble getPeriod4() {
		return period4;
	}
	public void setPeriod4(nc.vo.pub.lang.UFDouble period4) {
		this.period4 = period4;
	}
	public nc.vo.pub.lang.UFDouble getPeriod5() {
		return period5;
	}
	public void setPeriod5(nc.vo.pub.lang.UFDouble period5) {
		this.period5 = period5;
	}
	public nc.vo.pub.lang.UFDouble getPeriod6() {
		return period6;
	}
	public void setPeriod6(nc.vo.pub.lang.UFDouble period6) {
		this.period6 = period6;
	}
	public nc.vo.pub.lang.UFDouble getPeriod7() {
		return period7;
	}
	public void setPeriod7(nc.vo.pub.lang.UFDouble period7) {
		this.period7 = period7;
	}
	public nc.vo.pub.lang.UFDouble getPeriod8() {
		return period8;
	}
	public void setPeriod8(nc.vo.pub.lang.UFDouble period8) {
		this.period8 = period8;
	}
	
	public nc.vo.pub.lang.UFBoolean getIscancelaftercode() {
		return iscancelaftercode;
	}
	public void setIscancelaftercode(nc.vo.pub.lang.UFBoolean iscancelaftercode) {
		this.iscancelaftercode = iscancelaftercode;
	}
	
	public String getDeadline() {
		return deadline;
	}
	public void setDeadline(String deadline) {
		this.deadline = deadline;
	}
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_recstatement";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "arap_recstatement";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "arap_recstatement";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:
	 */
	public RecStatementVO() {
		super();
	}

	public IVOMeta getMetaData() {
		return VOMetaFactory.getInstance().getVOMeta("arap.arap_recstatement");
	}

}
