/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.arap.tally;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class RecStatementItemVO extends SuperVO {
	private java.lang.String pk_recstatement;
	private java.lang.String pk_recstatementitem;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String tallydate;
	private java.lang.String pk_customer;
	private java.lang.String pk_supplier;
	private java.lang.String pk_deptid;
	private java.lang.String pk_psndoc;
	private java.lang.String pk_currtype;
	private java.lang.String pk_billtype;
	private java.lang.String billtype;
	private java.lang.String pk_tradetypeid;
	private java.lang.String brief;
	private java.lang.String pk_bill;
	private java.lang.String billno;
	private java.lang.String invoiceno;
	private nc.vo.pub.lang.UFDouble debt_qua;
	private nc.vo.pub.lang.UFDouble debt_ori;
	private nc.vo.pub.lang.UFDouble debt_loc;
	private nc.vo.pub.lang.UFDouble gr_debt_loc;
	private nc.vo.pub.lang.UFDouble gl_debt_loc;
	private nc.vo.pub.lang.UFDouble credit_qua;
	private nc.vo.pub.lang.UFDouble credit_ori;
	private nc.vo.pub.lang.UFDouble credit_loc;
	private nc.vo.pub.lang.UFDouble gr_credit_loc;
	private nc.vo.pub.lang.UFDouble gl_credit_loc;
	private nc.vo.pub.lang.UFDouble bal_qua;
	private nc.vo.pub.lang.UFDouble bal_ori;
	private nc.vo.pub.lang.UFDouble bal_loc;
	private nc.vo.pub.lang.UFDouble gr_bal_loc;
	private nc.vo.pub.lang.UFDouble gl_bal_loc;
	private java.lang.Integer dealflag;
	private java.lang.String pk_dealnum;
	private java.lang.Integer markperiod;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private String matcustcode;
	private java.lang.String project;
	
	//add for 新加坡BDA 20161111
	private java.lang.String billno2;
	private java.lang.String busidate;
	private nc.vo.pub.lang.UFBoolean iscounterfee;
	//add end
	
	public static final String PK_RECSTATEMENT = "pk_recstatement";
	public static final String PK_RECSTATEMENTITEM = "pk_recstatementitem";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String TALLYDATE = "tallydate";
	public static final String PK_CUSTOMER = "pk_customer";
	public static final String PK_SUPPLIER = "pk_supplier";
	public static final String PK_DEPTID = "pk_deptid";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String BILLTYPE = "billtype";
	public static final String PK_TRADETYPEID = "pk_tradetypeid";
	public static final String BRIEF = "brief";
	public static final String PK_BILL = "pk_bill";
	public static final String BILLNO = "billno";
	public static final String INVOICENO = "invoiceno";
	public static final String DEBT_QUA = "debt_qua";
	public static final String DEBT_ORI = "debt_ori";
	public static final String DEBT_LOC = "debt_loc";
	public static final String GR_DEBT_LOC = "gr_debt_loc";
	public static final String GL_DEBT_LOC = "gl_debt_loc";
	public static final String CREDIT_QUA = "credit_qua";
	public static final String CREDIT_ORI = "credit_ori";
	public static final String CREDIT_LOC = "credit_loc";
	public static final String GR_CREDIT_LOC = "gr_credit_loc";
	public static final String GL_CREDIT_LOC = "gl_credit_loc";
	public static final String BAL_QUA = "bal_qua";
	public static final String BAL_ORI = "bal_ori";
	public static final String BAL_LOC = "bal_loc";
	public static final String GR_BAL_LOC = "gr_bal_loc";
	public static final String GL_BAL_LOC = "gl_bal_loc";
	public static final String DEALFLAG = "dealflag";
	public static final String PK_DEALNUM = "pk_dealnum";
	public static final String MARKPERIOD = "markperiod";
	public static final String MATCUSTCODE = "matcustcode";
	public static final String PROJECT = "project";
	public static final String BILLNO2 = "billno2";
	public static final String BUSIDATE = "busidate";
	public static final String ISCOUNTERFEE = "iscounterfee";
	
	
	/**
	 * 属性pk_recstatement的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_recstatement () {
		return pk_recstatement;
	}   
	/**
	 * 属性pk_recstatement的Setter方法.
	 * 创建日期:
	 * @param newPk_recstatement java.lang.String
	 */
	public void setPk_recstatement (java.lang.String newPk_recstatement ) {
	 	this.pk_recstatement = newPk_recstatement;
	} 	  
	/**
	 * 属性pk_recstatementitem的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_recstatementitem () {
		return pk_recstatementitem;
	}   
	/**
	 * 属性pk_recstatementitem的Setter方法.
	 * 创建日期:
	 * @param newPk_recstatementitem java.lang.String
	 */
	public void setPk_recstatementitem (java.lang.String newPk_recstatementitem ) {
	 	this.pk_recstatementitem = newPk_recstatementitem;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性tallydate的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTallydate () {
		return tallydate;
	}   
	/**
	 * 属性tallydate的Setter方法.
	 * 创建日期:
	 * @param newTallydate java.lang.String
	 */
	public void setTallydate (java.lang.String newTallydate ) {
	 	this.tallydate = newTallydate;
	} 	  
	/**
	 * 属性pk_customer的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_customer () {
		return pk_customer;
	}   
	/**
	 * 属性pk_customer的Setter方法.
	 * 创建日期:
	 * @param newPk_customer java.lang.String
	 */
	public void setPk_customer (java.lang.String newPk_customer ) {
	 	this.pk_customer = newPk_customer;
	} 	  
	/**
	 * 属性pk_supplier的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_supplier () {
		return pk_supplier;
	}   
	/**
	 * 属性pk_supplier的Setter方法.
	 * 创建日期:
	 * @param newPk_supplier java.lang.String
	 */
	public void setPk_supplier (java.lang.String newPk_supplier ) {
	 	this.pk_supplier = newPk_supplier;
	} 	  
	/**
	 * 属性pk_deptid的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_deptid () {
		return pk_deptid;
	}   
	/**
	 * 属性pk_deptid的Setter方法.
	 * 创建日期:
	 * @param newPk_deptid java.lang.String
	 */
	public void setPk_deptid (java.lang.String newPk_deptid ) {
	 	this.pk_deptid = newPk_deptid;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:
	 * @param newPk_psndoc java.lang.String
	 */
	public void setPk_psndoc (java.lang.String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性pk_currtype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_currtype () {
		return pk_currtype;
	}   
	/**
	 * 属性pk_currtype的Setter方法.
	 * 创建日期:
	 * @param newPk_currtype java.lang.String
	 */
	public void setPk_currtype (java.lang.String newPk_currtype ) {
	 	this.pk_currtype = newPk_currtype;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:
	 * @param newPk_billtype java.lang.String
	 */
	public void setPk_billtype (java.lang.String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	public java.lang.String getBilltype() {
		return billtype;
	}
	public void setBilltype(java.lang.String billtype) {
		this.billtype = billtype;
	}
	/**
	 * 属性pk_tradetypeid的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tradetypeid () {
		return pk_tradetypeid;
	}   
	/**
	 * 属性pk_tradetypeid的Setter方法.
	 * 创建日期:
	 * @param newPk_tradetypeid java.lang.String
	 */
	public void setPk_tradetypeid (java.lang.String newPk_tradetypeid ) {
	 	this.pk_tradetypeid = newPk_tradetypeid;
	} 	  
	/**
	 * 属性brief的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBrief () {
		return brief;
	}   
	/**
	 * 属性brief的Setter方法.
	 * 创建日期:
	 * @param newBrief java.lang.String
	 */
	public void setBrief (java.lang.String newBrief ) {
	 	this.brief = newBrief;
	} 	  
	/**
	 * 属性pk_bill的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bill () {
		return pk_bill;
	}   
	/**
	 * 属性pk_bill的Setter方法.
	 * 创建日期:
	 * @param newPk_bill java.lang.String
	 */
	public void setPk_bill (java.lang.String newPk_bill ) {
	 	this.pk_bill = newPk_bill;
	} 	  
	/**
	 * 属性billno的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno () {
		return billno;
	}   
	/**
	 * 属性billno的Setter方法.
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno (java.lang.String newBillno ) {
	 	this.billno = newBillno;
	} 	  
	/**
	 * 属性invoiceno的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getInvoiceno () {
		return invoiceno;
	}   
	/**
	 * 属性invoiceno的Setter方法.
	 * 创建日期:
	 * @param newInvoiceno java.lang.String
	 */
	public void setInvoiceno (java.lang.String newInvoiceno ) {
	 	this.invoiceno = newInvoiceno;
	} 	  
	/**
	 * 属性debt_qua的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDebt_qua () {
		return debt_qua;
	}   
	/**
	 * 属性debt_qua的Setter方法.
	 * 创建日期:
	 * @param newDebt_qua nc.vo.pub.lang.UFDouble
	 */
	public void setDebt_qua (nc.vo.pub.lang.UFDouble newDebt_qua ) {
	 	this.debt_qua = newDebt_qua;
	} 	  
	/**
	 * 属性debt_ori的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDebt_ori () {
		return debt_ori;
	}   
	/**
	 * 属性debt_ori的Setter方法.
	 * 创建日期:
	 * @param newDebt_ori nc.vo.pub.lang.UFDouble
	 */
	public void setDebt_ori (nc.vo.pub.lang.UFDouble newDebt_ori ) {
	 	this.debt_ori = newDebt_ori;
	} 	  
	/**
	 * 属性debt_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getDebt_loc () {
		return debt_loc;
	}   
	/**
	 * 属性debt_loc的Setter方法.
	 * 创建日期:
	 * @param newDebt_loc nc.vo.pub.lang.UFDouble
	 */
	public void setDebt_loc (nc.vo.pub.lang.UFDouble newDebt_loc ) {
	 	this.debt_loc = newDebt_loc;
	} 	  
	/**
	 * 属性gr_debt_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGr_debt_loc () {
		return gr_debt_loc;
	}   
	/**
	 * 属性gr_debt_loc的Setter方法.
	 * 创建日期:
	 * @param newGr_debt_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGr_debt_loc (nc.vo.pub.lang.UFDouble newGr_debt_loc ) {
	 	this.gr_debt_loc = newGr_debt_loc;
	} 	  
	/**
	 * 属性gl_debt_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGl_debt_loc () {
		return gl_debt_loc;
	}   
	/**
	 * 属性gl_debt_loc的Setter方法.
	 * 创建日期:
	 * @param newGl_debt_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGl_debt_loc (nc.vo.pub.lang.UFDouble newGl_debt_loc ) {
	 	this.gl_debt_loc = newGl_debt_loc;
	} 	  
	/**
	 * 属性credit_qua的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getCredit_qua () {
		return credit_qua;
	}   
	/**
	 * 属性credit_qua的Setter方法.
	 * 创建日期:
	 * @param newCredit_qua nc.vo.pub.lang.UFDouble
	 */
	public void setCredit_qua (nc.vo.pub.lang.UFDouble newCredit_qua ) {
	 	this.credit_qua = newCredit_qua;
	} 	  
	/**
	 * 属性credit_ori的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getCredit_ori () {
		return credit_ori;
	}   
	/**
	 * 属性credit_ori的Setter方法.
	 * 创建日期:
	 * @param newCredit_ori nc.vo.pub.lang.UFDouble
	 */
	public void setCredit_ori (nc.vo.pub.lang.UFDouble newCredit_ori ) {
	 	this.credit_ori = newCredit_ori;
	} 	  
	/**
	 * 属性credit_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getCredit_loc () {
		return credit_loc;
	}   
	/**
	 * 属性credit_loc的Setter方法.
	 * 创建日期:
	 * @param newCredit_loc nc.vo.pub.lang.UFDouble
	 */
	public void setCredit_loc (nc.vo.pub.lang.UFDouble newCredit_loc ) {
	 	this.credit_loc = newCredit_loc;
	} 	  
	/**
	 * 属性gr_credit_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGr_credit_loc () {
		return gr_credit_loc;
	}   
	/**
	 * 属性gr_credit_loc的Setter方法.
	 * 创建日期:
	 * @param newGr_credit_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGr_credit_loc (nc.vo.pub.lang.UFDouble newGr_credit_loc ) {
	 	this.gr_credit_loc = newGr_credit_loc;
	} 	  
	/**
	 * 属性gl_credit_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGl_credit_loc () {
		return gl_credit_loc;
	}   
	/**
	 * 属性gl_credit_loc的Setter方法.
	 * 创建日期:
	 * @param newGl_credit_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGl_credit_loc (nc.vo.pub.lang.UFDouble newGl_credit_loc ) {
	 	this.gl_credit_loc = newGl_credit_loc;
	} 	  
	/**
	 * 属性bal_qua的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_qua () {
		return bal_qua;
	}   
	/**
	 * 属性bal_qua的Setter方法.
	 * 创建日期:
	 * @param newBal_qua nc.vo.pub.lang.UFDouble
	 */
	public void setBal_qua (nc.vo.pub.lang.UFDouble newBal_qua ) {
	 	this.bal_qua = newBal_qua;
	} 	  
	/**
	 * 属性bal_ori的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_ori () {
		return bal_ori;
	}   
	/**
	 * 属性bal_ori的Setter方法.
	 * 创建日期:
	 * @param newBal_ori nc.vo.pub.lang.UFDouble
	 */
	public void setBal_ori (nc.vo.pub.lang.UFDouble newBal_ori ) {
	 	this.bal_ori = newBal_ori;
	} 	  
	/**
	 * 属性bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getBal_loc () {
		return bal_loc;
	}   
	/**
	 * 属性bal_loc的Setter方法.
	 * 创建日期:
	 * @param newBal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setBal_loc (nc.vo.pub.lang.UFDouble newBal_loc ) {
	 	this.bal_loc = newBal_loc;
	} 	  
	/**
	 * 属性gr_bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGr_bal_loc () {
		return gr_bal_loc;
	}   
	/**
	 * 属性gr_bal_loc的Setter方法.
	 * 创建日期:
	 * @param newGr_bal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGr_bal_loc (nc.vo.pub.lang.UFDouble newGr_bal_loc ) {
	 	this.gr_bal_loc = newGr_bal_loc;
	} 	  
	/**
	 * 属性gl_bal_loc的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGl_bal_loc () {
		return gl_bal_loc;
	}   
	/**
	 * 属性gl_bal_loc的Setter方法.
	 * 创建日期:
	 * @param newGl_bal_loc nc.vo.pub.lang.UFDouble
	 */
	public void setGl_bal_loc (nc.vo.pub.lang.UFDouble newGl_bal_loc ) {
	 	this.gl_bal_loc = newGl_bal_loc;
	} 	  
	/**
	 * 属性dealflag的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDealflag () {
		return dealflag;
	}   
	/**
	 * 属性dealflag的Setter方法.
	 * 创建日期:
	 * @param newDealflag java.lang.Integer
	 */
	public void setDealflag (java.lang.Integer newDealflag ) {
	 	this.dealflag = newDealflag;
	} 	  
	/**
	 * 属性pk_dealnum的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dealnum () {
		return pk_dealnum;
	}   
	/**
	 * 属性pk_dealnum的Setter方法.
	 * 创建日期:
	 * @param newPk_dealnum java.lang.String
	 */
	public void setPk_dealnum (java.lang.String newPk_dealnum ) {
	 	this.pk_dealnum = newPk_dealnum;
	} 	  
	/**
	 * 属性markperiod的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getMarkperiod () {
		return markperiod;
	}   
	/**
	 * 属性markperiod的Setter方法.
	 * 创建日期:
	 * @param newMarkperiod java.lang.Integer
	 */
	public void setMarkperiod (java.lang.Integer newMarkperiod ) {
	 	this.markperiod = newMarkperiod;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_recstatement";
	}   
	public String getMatcustcode() {
		return matcustcode;
	}
	public void setMatcustcode(String matcustcode) {
		this.matcustcode = matcustcode;
	}
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_recstatementitem";
	}
    
	/**
	 * 属性billno2的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillno2 () {
		return billno2;
	}   
	/**
	 * 属性busidate的Setter方法.
	 * 创建日期:
	 * @param busidate java.lang.String
	 */
	public void setBusidate (java.lang.String busidate ) {
	 	this.busidate = busidate;
	} 	
	
	/**
	 * 属性busidate的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusidate () {
		return busidate;
	}   
	/**
	 * 属性billno2的Setter方法.
	 * 创建日期:
	 * @param newBillno java.lang.String
	 */
	public void setBillno2 (java.lang.String newBillno2 ) {
	 	this.billno2 = newBillno2;
	}	
	
	public nc.vo.pub.lang.UFBoolean getIscounterfee() {
		return iscounterfee;
	}
	public void setIscounterfee(nc.vo.pub.lang.UFBoolean iscounterfee) {
		this.iscounterfee = iscounterfee;
	}
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "arap_recstatementitem";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "arap_recstatementitem";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public RecStatementItemVO() {
		super();	
	}    
	
	public IVOMeta getMetaData() {
		return VOMetaFactory.getInstance().getVOMeta("arap.arap_recstatementitem");
	}
	public void setProject(java.lang.String project) {
		this.project = project;
	}
	public java.lang.String getProject() {
		return project;
	}
} 


